# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wide_region', models.CharField(max_length=5)),
                ('election_district', models.CharField(max_length=20)),
                ('tactic_order', models.IntegerField()),
                ('admin_region', models.CharField(max_length=10)),
                ('minju_avg', models.FloatField()),
                ('minju_act', models.FloatField()),
                ('minju_pas', models.FloatField()),
                ('third_val', models.FloatField()),
                ('sanuri_avg', models.FloatField()),
                ('sanuri_act', models.FloatField()),
                ('sanuri_pas', models.FloatField()),
            ],
        ),
    ]
