# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votenewslab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteregion',
            name='region_id',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
