# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votenewslab', '0002_voteregion_region_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_name', models.CharField(max_length=10)),
                ('meta_title', models.CharField(max_length=20)),
                ('meta_type', models.CharField(max_length=15)),
                ('meta_url', models.TextField()),
                ('meta_description', models.TextField()),
                ('meta_image', models.TextField()),
            ],
        ),
    ]
