# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votenewslab', '0003_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cand_name', models.CharField(max_length=5)),
                ('cand_party_color', models.CharField(max_length=8)),
                ('cand_region_id', models.CharField(max_length=10)),
                ('cand_profile', models.TextField()),
                ('cand_id', models.CharField(max_length=10)),
            ],
        ),
    ]
