# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votenewslab', '0004_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteregion',
            name='minju_trg',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voteregion',
            name='sanuri_trg',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
    ]
