# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votenewslab', '0005_auto_20160404_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cand_region_id',
            field=models.CharField(max_length=50),
        ),
    ]
