# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votenewslab', '0007_auto_20160404_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteregion',
            name='tactic_order',
        ),
    ]
