# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votenewslab', '0009_auto_20160405_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteregion',
            name='region_id',
            field=models.CharField(max_length=100),
        ),
    ]
