# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votenewslab', '0010_auto_20160405_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cand_number',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
