# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0004_auto_20160128_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoice',
            name='chosen',
            field=models.TextField(default=''),
        ),
    ]
