# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0006_nin2content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nin2content',
            old_name='explain',
            new_name='n2c_explain',
        ),
        migrations.RenameField(
            model_name='nin2content',
            old_name='url',
            new_name='n2c_path',
        ),
        migrations.RenameField(
            model_name='nin2content',
            old_name='title',
            new_name='n2c_title',
        ),
    ]
