# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0009_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('explain', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_baord', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('idx', models.IntegerField()),
                ('result_str', models.TextField(default='')),
                ('explain_str', models.TextField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_name',
            new_name='name',
        ),
    ]
