# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0010_auto_20160203_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logic',
            old_name='score_baord',
            new_name='score_board',
        ),
    ]
