# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 04:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0011_auto_20160203_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 2, 3, 4, 54, 1, 840392, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
