# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0012_home_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='logic',
            name='name',
            field=models.CharField(default='asdf', max_length=10),
            preserve_default=False,
        ),
    ]
