# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0015_countrypay'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableModals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_id', models.CharField(max_length=10)),
                ('modal_title', models.CharField(max_length=25)),
                ('modal_body', models.TextField()),
            ],
        ),
    ]
