# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0018_auto_20160210_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoice',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
