# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0019_auto_20160210_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemodal',
            name='modal_name',
            field=models.CharField(default='\ucc44\uc6cc \ub123\uc5b4\ub77c', max_length=10),
            preserve_default=False,
        ),
    ]
