# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0022_auto_20160215_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='modal',
            name='name',
            field=models.CharField(default='calc', max_length=10),
            preserve_default=False,
        ),
    ]
