# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0023_modal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='input_type',
            field=models.TextField(default=''),
        ),
    ]
