# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0024_home_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='input_type',
            field=models.TextField(default='type/name/id/placeholder'),
        ),
    ]
