# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0025_auto_20160215_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='urjson',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='input_type',
            field=models.TextField(default='label/type/name/id/placeholder'),
        ),
    ]
