# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0028_auto_20160216_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchoice',
            name='chosen',
        ),
        migrations.AddField(
            model_name='userchoice',
            name='name',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='chosen_json',
            field=models.TextField(default='{}'),
        ),
    ]
