# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0029_auto_20160217_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='option',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='user_json',
            field=models.TextField(default='{}'),
        ),
    ]
