# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0030_auto_20160218_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Univ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('avg', models.IntegerField()),
                ('soc', models.IntegerField()),
                ('sci', models.IntegerField()),
                ('art', models.IntegerField()),
                ('eng', models.IntegerField()),
                ('med', models.IntegerField()),
            ],
        ),
    ]
