# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0031_univ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='univ',
            name='avg',
        ),
    ]
