# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0032_remove_univ_avg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nin2Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('card_content', models.TextField()),
                ('card_reveal_title', models.CharField(max_length=20)),
                ('card_reveal_content', models.TextField()),
            ],
        ),
    ]
