# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0036_remove_problem_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='BofuEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_from', models.IntegerField()),
                ('edge_to', models.IntegerField()),
                ('edge_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BofuInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intv_name', models.CharField(max_length=30)),
                ('intv_quote', models.TextField()),
                ('intv_icon', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BofuNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField()),
                ('node_value', models.IntegerField()),
                ('node_label', models.CharField(max_length=7)),
                ('node_pos', models.CharField(max_length=4)),
            ],
        ),
    ]
