# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0037_bofuedge_bofuinterview_bofunode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bofuedge',
            name='edge_json',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bofunode',
            name='node_json',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
