# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0038_auto_20160306_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=10)),
                ('meta_title', models.CharField(max_length=20)),
                ('meta_type', models.CharField(max_length=10)),
                ('meta_url', models.TextField()),
                ('meta_description', models.TextField()),
                ('meta_image', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='bofuinterview',
            name='intv_key',
            field=models.CharField(default='null', max_length=5),
            preserve_default=False,
        ),
    ]
