# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0039_auto_20160306_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meta',
            old_name='meta_key',
            new_name='meta_name',
        ),
    ]
