# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0040_auto_20160306_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryPay',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='meta',
            name='meta_type',
            field=models.CharField(max_length=15),
        ),
    ]
