# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0041_auto_20160306_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nin2result',
            name='card_reveal_title',
            field=models.CharField(max_length=30),
        ),
    ]
