# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0042_auto_20160308_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='nin2result',
            name='link_url',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
