# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin2newslab', '0043_nin2result_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bofuinterview',
            name='intv_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bofuinterview',
            name='intv_icon',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='bofuinterview',
            name='intv_key',
            field=models.CharField(max_length=15),
        ),
    ]
